var searchData=
[
  ['same_20binary_20executable_20dll_0',['Can different versions of the framework be used within the same binary (executable/dll)?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md137',1,'']]],
  ['saveargaction_1',['SaveArgAction',['../structtesting_1_1internal_1_1SaveArgAction.html',1,'testing::internal']]],
  ['saveargpointeeaction_2',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1SaveArgPointeeAction.html',1,'testing::internal']]],
  ['scaling_20up_3',['Scaling up',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2tutorial.html#autotoc_md181',1,'']]],
  ['scan_5fargs_4',['scan_args',['../structscan__args.html',1,'']]],
  ['scan_5fbuffer_5',['scan_buffer',['../classdetail_1_1scan__buffer.html',1,'detail']]],
  ['scan_5fcontext_6',['scan_context',['../classscan__context.html',1,'']]],
  ['scan_5fhandler_7',['scan_handler',['../structdetail_1_1scan__handler.html',1,'detail']]],
  ['scan_5fparse_5fcontext_8',['scan_parse_context',['../classscan__parse__context.html',1,'']]],
  ['scanner_9',['scanner',['../structscanner.html',1,'']]],
  ['scanner_3c_20num_20_3e_10',['scanner&lt; num &gt;',['../structfmt_1_1scanner_3_01num_01_4.html',1,'fmt']]],
  ['scoped_5fmock_11',['scoped_mock',['../structscoped__mock.html',1,'']]],
  ['scopedprematureexitfile_12',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1ScopedPrematureExitFile.html',1,'testing::internal']]],
  ['scopedtrace_13',['ScopedTrace',['../classtesting_1_1ScopedTrace.html',1,'testing']]],
  ['security_20policy_14',['Security Policy',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md272',1,'']]],
  ['sentinel_15',['sentinel',['../classdetail_1_1scan__buffer_1_1sentinel.html',1,'detail::scan_buffer']]],
  ['set_16',['set',['../classdetail_1_1buffer.html#a5c82aec716b07079ac88194eb9aa7feb',1,'detail::buffer']]],
  ['setargrefereeaction_17',['SetArgRefereeAction',['../structtesting_1_1internal_1_1SetArgRefereeAction.html',1,'testing::internal']]],
  ['setargumentpointeeaction_18',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1SetArgumentPointeeAction.html',1,'testing::internal']]],
  ['setarrayargumentaction_19',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1SetArrayArgumentAction.html',1,'testing::internal']]],
  ['seterrnoandreturnaction_20',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1SetErrnoAndReturnAction.html',1,'testing::internal']]],
  ['shared_20objects_20dlls_21',['Dealing with shared objects (DLLs)',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2main.html#autotoc_md152',1,'']]],
  ['should_5fstringify_5fas_5funderlying_5ftype_22',['should_stringify_as_underlying_type',['../structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html',1,'doctest::detail']]],
  ['simple_20example_23',['A simple example',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2tutorial.html#autotoc_md178',1,'']]],
  ['singleton_24',['singleton',['../structdetail_1_1singleton.html',1,'detail']]],
  ['size_25',['size',['../structformat__to__n__result.html#ab1c815078e1a78716bb07b9ed8c7023b',1,'format_to_n_result::size'],['../classbasic__string__view.html#a216bbe1b012b590698d7bb4e96d1af3f',1,'basic_string_view::size()'],['../classdetail_1_1buffer.html#a8685285932360c284d19003fc4ba3edc',1,'detail::buffer::size()'],['../classformat__int.html#a2f1870d4b535ead8699717fdcb25e997',1,'format_int::size()'],['../classmgutility_1_1enum__for__each.html#a0d833b4ee26998c4373aee17be12cd90',1,'mgutility::enum_for_each::size()'],['../classmgutility_1_1basic__string__view.html#a26e96c7b63f54ccd9306e3a4ecf5b336',1,'mgutility::basic_string_view::size()']]],
  ['slow_5ffloat_26',['slow_float',['../structslow__float.html',1,'']]],
  ['small_5fgrouping_27',['small_grouping',['../structsmall__grouping.html',1,'']]],
  ['somefixture_28',['SomeFixture',['../structSomeFixture.html',1,'']]],
  ['special_5fgrouping_29',['special_grouping',['../structspecial__grouping.html',1,'']]],
  ['specialisation_30',['&lt;tt&gt;doctest::StringMaker\&lt;T\&gt;&lt;/tt&gt; specialisation',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2stringification.html#autotoc_md166',1,'']]],
  ['speed_20tests_31',['Speed tests',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md258',1,'']]],
  ['spirit_20karma_32',['Boost Spirit.Karma',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md268',1,'']]],
  ['stargazers_20over_20time_33',['Stargazers over time',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2README.html#autotoc_md186',1,'']]],
  ['static_20library_20not_20getting_20registered_34',['Why are my tests in a static library not getting registered?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md132',1,'']]],
  ['std_3a_3aostream_20tt_35',['&lt;tt&gt;operator\&lt;\&lt;&lt;/tt&gt; overload for &lt;tt&gt;std::ostream&lt;/tt&gt;',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2stringification.html#autotoc_md164',1,'']]],
  ['std_5fstring_5fview_36',['std_string_view',['../structdetail_1_1std__string__view.html',1,'detail']]],
  ['steps_37',['Next steps',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2tutorial.html#autotoc_md182',1,'']]],
  ['stl_20headers_20when_20including_20the_20doctest_20header_38',['Why do I get compiler errors in STL headers when including the doctest header?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md136',1,'']]],
  ['stlcontainerview_39',['StlContainerView',['../classtesting_1_1internal_1_1StlContainerView.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_40',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1StlContainerView_3_01_1_1std_1_1tuple_3_01ElementPointer_00_01Size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_41',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1StlContainerView_3_01Element_0fN_0e_4.html',1,'testing::internal']]],
  ['str_42',['str',['../classformat__int.html#a0f1b5493b06b98edb747737ba864f86f',1,'format_int']]],
  ['streamable_5fand_5funformattable_43',['streamable_and_unformattable',['../structstreamable__and__unformattable.html',1,'']]],
  ['streamed_5fview_44',['streamed_view',['../structdetail_1_1streamed__view.html',1,'detail']]],
  ['streamprinter_45',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1StreamPrinter.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strictmock_46',['StrictMock',['../classtesting_1_1StrictMock.html',1,'testing']]],
  ['strictmock_3c_20mock_20_3e_47',['StrictMock&lt; Mock &gt;',['../classtesting_1_1StrictMock.html',1,'testing']]],
  ['strictmockimpl_48',['StrictMockImpl',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mock_20_3e_49',['StrictMockImpl&lt; Mock &gt;',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_50',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['string_51',['string',['../structadl__test_1_1string.html',1,'adl_test']]],
  ['string_52',['String',['../classdoctest_1_1String.html',1,'doctest::String'],['../classtesting_1_1internal_1_1String.html',1,'testing::internal::String']]],
  ['string_20containment_53',['String containment',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2assertions.html#autotoc_md53',1,'']]],
  ['string_20conversions_54',['String conversions',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2stringification.html',1,'']]],
  ['string_5fliteral_55',['string_literal',['../structdetail_1_1string__literal.html',1,'detail']]],
  ['string_5fscan_5fbuffer_56',['string_scan_buffer',['../classdetail_1_1string__scan__buffer.html',1,'detail']]],
  ['string_5fvalue_57',['string_value',['../structdetail_1_1string__value.html',1,'detail']]],
  ['string_5fvalue_3c_20char_5ftype_20_3e_58',['string_value&lt; char_type &gt;',['../structdetail_1_1string__value.html',1,'detail']]],
  ['stringcontains_59',['StringContains',['../classdoctest_1_1AssertData_1_1StringContains.html',1,'doctest::AssertData']]],
  ['stringmaker_60',['StringMaker',['../structdoctest_1_1StringMaker.html',1,'doctest']]],
  ['stringmaker_3c_20std_3a_3alist_3c_20t_20_3e_20_3e_61',['StringMaker&lt; std::list&lt; T &gt; &gt;',['../structdoctest_1_1StringMaker_3_01std_1_1list_3_01T_01_4_01_4.html',1,'doctest']]],
  ['stringmakerbase_62',['StringMakerBase',['../structdoctest_1_1detail_1_1StringMakerBase.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20detail_3a_3ahas_5finsertion_5foperator_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5fpointer_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5farray_3c_20t_20_3e_3a_3avalue_20_3e_63',['StringMakerBase&lt; detail::has_insertion_operator&lt; T &gt;::value||detail::types::is_pointer&lt; T &gt;::value||detail::types::is_array&lt; T &gt;::value &gt;',['../structdoctest_1_1detail_1_1StringMakerBase.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20true_20_3e_64',['StringMakerBase&lt; true &gt;',['../structdoctest_1_1detail_1_1StringMakerBase_3_01true_01_4.html',1,'doctest::detail']]],
  ['strings_20tt_20char_20tt_20actually_20comparing_20pointers_65',['Why is comparing C strings (&lt;tt&gt;char*&lt;/tt&gt;) actually comparing pointers?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md133',1,'']]],
  ['strip_5fnamed_5farg_66',['strip_named_arg',['../structdetail_1_1strip__named__arg.html',1,'detail']]],
  ['strip_5fnamed_5farg_3c_20t_2c_20true_20_3e_67',['strip_named_arg&lt; T, true &gt;',['../structdetail_1_1strip__named__arg_3_01T_00_01true_01_4.html',1,'detail']]],
  ['strong_20doctest_20strong_20different_20from_20catch_68',['How is &lt;strong&gt;doctest&lt;/strong&gt; different from Catch?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md127',1,'']]],
  ['strong_20doctest_20strong_20different_20from_20google_20test_69',['How is &lt;strong&gt;doctest&lt;/strong&gt; different from Google Test?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md128',1,'']]],
  ['struct_5fas_5fconst_5freference_70',['struct_as_const_reference',['../structtest_1_1struct__as__const__reference.html',1,'test']]],
  ['struct_5fas_5fint_71',['struct_as_int',['../structtest_1_1struct__as__int.html',1,'test']]],
  ['struct_5fas_5fwstring_5fview_72',['struct_as_wstring_view',['../structtest_1_1struct__as__wstring__view.html',1,'test']]],
  ['style_20test_20cases_73',['BDD-style test cases',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2testcases.html#autotoc_md171',1,'']]],
  ['styled_5farg_74',['styled_arg',['../structdetail_1_1styled__arg.html',1,'detail']]],
  ['subcase_75',['Subcase',['../structdoctest_1_1detail_1_1Subcase.html',1,'doctest::detail::Subcase'],['../structSubcase.html',1,'Subcase']]],
  ['subcases_76',['Test cases and subcases',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2tutorial.html#autotoc_md180',1,'']]],
  ['subcasesignature_77',['SubcaseSignature',['../structdoctest_1_1SubcaseSignature.html',1,'doctest']]],
  ['substr_78',['substr',['../classmgutility_1_1basic__string__view.html#afaa73ee06ad76de37e100e06f98822ee',1,'mgutility::basic_string_view']]],
  ['suiteapiresolver_79',['SuiteApiResolver',['../structtesting_1_1internal_1_1SuiteApiResolver.html',1,'testing::internal']]],
  ['suites_80',['Test suites',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2testcases.html#autotoc_md173',1,'']]],
  ['support_81',['Bazel support',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2support_2bazel_2README.html',1,'']]],
  ['supported_82',['Is mocking supported?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md131',1,'']]],
  ['supported_20compilers_83',['Supported Compilers',['../md__2home_2runner_2work_2enum__name_2enum__name_2README.html#autotoc_md279',1,'']]],
  ['swap_84',['swap',['../classmgutility_1_1optional.html#a5b5ec8a5d27ada527e1a769470c7a7c4',1,'mgutility::optional']]],
  ['systems_85',['Build systems',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2build-systems.html',1,'']]]
];
