var searchData=
[
  ['b_0',['B',['../structN_1_1B.html',1,'N']]],
  ['bad_5fformat_1',['bad_format',['../structbad__format.html',1,'']]],
  ['bad_5foptional_5faccess_2',['bad_optional_access',['../structmgutility_1_1bad__optional__access.html',1,'mgutility']]],
  ['basic_5fcstring_5fview_3',['basic_cstring_view',['../classbasic__cstring__view.html',1,'basic_cstring_view&lt; Char &gt;'],['../classbasic__cstring__view.html#ab464b2378652892cec4716d3e3d475c7',1,'basic_cstring_view::basic_cstring_view(const Char *s)'],['../classbasic__cstring__view.html#a10b92cc0e3e67789601984099b9ed339',1,'basic_cstring_view::basic_cstring_view(const std::basic_string&lt; Char &gt; &amp;s)']]],
  ['basic_5fformat_5farg_4',['basic_format_arg',['../classbasic__format__arg.html',1,'']]],
  ['basic_5fformat_5farg_3c_20basic_5fformat_5fcontext_20_3e_5',['basic_format_arg&lt; basic_format_context &gt;',['../classbasic__format__arg.html',1,'']]],
  ['basic_5fformat_5fargs_6',['basic_format_args',['../classbasic__format__args.html',1,'basic_format_args&lt; Context &gt;'],['../classbasic__format__args.html#ac40bdd2deb4a1000df76553387588775',1,'basic_format_args::basic_format_args(const format_arg_store&lt; Context, Args... &gt; &amp;store)'],['../classbasic__format__args.html#a69dd0f6fb0e95f42f57cc3bfb095a397',1,'basic_format_args::basic_format_args(const dynamic_format_arg_store&lt; Context &gt; &amp;store)'],['../classbasic__format__args.html#a1b6a098d11577f454964b51c2d7f9027',1,'basic_format_args::basic_format_args(const format_arg *args, int count)']]],
  ['basic_5fformat_5fargs_3c_20basic_5fformat_5fcontext_20_3e_7',['basic_format_args&lt; basic_format_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fargs_3c_20basic_5fprintf_5fcontext_20_3e_8',['basic_format_args&lt; basic_printf_context &gt;',['../classbasic__format__args.html',1,'']]],
  ['basic_5fformat_5fcontext_9',['basic_format_context',['../classbasic__format__context.html',1,'basic_format_context&lt; OutputIt, Char &gt;'],['../classbasic__format__context.html#af9f83b3b640bc3cb8d6cb93332bb27a1',1,'basic_format_context::basic_format_context()']]],
  ['basic_5fformat_5fparse_5fcontext_10',['basic_format_parse_context',['../classbasic__format__parse__context.html',1,'']]],
  ['basic_5fformat_5fstring_11',['basic_format_string',['../classbasic__format__string.html',1,'']]],
  ['basic_5ffp_12',['basic_fp',['../structdetail_1_1basic__fp.html',1,'detail']]],
  ['basic_5fistream_13',['basic_istream',['../classstd_1_1basic__istream.html',1,'std']]],
  ['basic_5fmemory_5fbuffer_14',['basic_memory_buffer',['../classbasic__memory__buffer.html',1,'basic_memory_buffer&lt; T, SIZE, Allocator &gt;'],['../classbasic__memory__buffer.html#ade18cff12fc914085665a07af2e8fb7b',1,'basic_memory_buffer::basic_memory_buffer()']]],
  ['basic_5fmemory_5fbuffer_3c_20bigit_2c_20bigits_5fcapacity_20_3e_15',['basic_memory_buffer&lt; bigit, bigits_capacity &gt;',['../classbasic__memory__buffer.html',1,'']]],
  ['basic_5fmemory_5fbuffer_3c_20wchar_5ft_20_3e_16',['basic_memory_buffer&lt; wchar_t &gt;',['../classbasic__memory__buffer.html',1,'']]],
  ['basic_5fostream_17',['basic_ostream',['../classstd_1_1basic__ostream.html',1,'std']]],
  ['basic_5fostream_5fformatter_18',['basic_ostream_formatter',['../structbasic__ostream__formatter.html',1,'']]],
  ['basic_5fostream_5fformatter_3c_20wchar_5ft_20_3e_19',['basic_ostream_formatter&lt; wchar_t &gt;',['../structbasic__ostream__formatter.html',1,'']]],
  ['basic_5fprintf_5fcontext_20',['basic_printf_context',['../classbasic__printf__context.html',1,'basic_printf_context&lt; Char &gt;'],['../classbasic__printf__context.html#a34c89760bb25aa1b6c40b912127a1189',1,'basic_printf_context::basic_printf_context()']]],
  ['basic_5fscan_5farg_21',['basic_scan_arg',['../classbasic__scan__arg.html',1,'']]],
  ['basic_5fstring_5fview_22',['basic_string_view',['../classbasic__string__view.html',1,'basic_string_view&lt; Char &gt;'],['../classmgutility_1_1basic__string__view.html',1,'mgutility::basic_string_view&lt; Char &gt;'],['../classbasic__string__view.html#aae708273ca864680a424c10441799605',1,'basic_string_view::basic_string_view(const Char *s, size_t count) noexcept'],['../classbasic__string__view.html#a961254412253f97e1273cdaacb1af1a3',1,'basic_string_view::basic_string_view(const Char *s)'],['../classbasic__string__view.html#a05e308de94ccd7f6203ba3ea94f68ebd',1,'basic_string_view::basic_string_view(const std::basic_string&lt; Char, Traits, Alloc &gt; &amp;s) noexcept'],['../classmgutility_1_1basic__string__view.html#a98047372022acfb78fbeb82ff7aa5190',1,'mgutility::basic_string_view::basic_string_view() noexcept'],['../classmgutility_1_1basic__string__view.html#a07cc48696b3095ed0b79327b3a423fe6',1,'mgutility::basic_string_view::basic_string_view(const Char *str) noexcept'],['../classmgutility_1_1basic__string__view.html#ab8993982c8b6cc334f448f440d5f368d',1,'mgutility::basic_string_view::basic_string_view(const std::basic_string&lt; Char &gt; &amp;str) noexcept'],['../classmgutility_1_1basic__string__view.html#ac3d4a66987b79b36a6207a7d9c85a5ba',1,'mgutility::basic_string_view::basic_string_view(const Char *str, size_t len) noexcept'],['../classmgutility_1_1basic__string__view.html#a25e8d6ef98e904e1848fb80fe806b2db',1,'mgutility::basic_string_view::basic_string_view(const basic_string_view &amp;other)'],['../classmgutility_1_1basic__string__view.html#a3bf92ec244076c7a71569d64bddc7e3e',1,'mgutility::basic_string_view::basic_string_view(basic_string_view &amp;&amp;other) noexcept']]],
  ['basic_5fstring_5fview_3c_20char_20_3e_23',['basic_string_view&lt; char &gt;',['../classbasic__string__view.html',1,'']]],
  ['basic_5fstring_5fview_3c_20char_5ftype_20_3e_24',['basic_string_view&lt; char_type &gt;',['../classbasic__string__view.html',1,'']]],
  ['basic_5ftest_5fstring_25',['basic_test_string',['../classbasic__test__string.html',1,'']]],
  ['bazel_20support_26',['Bazel support',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2support_2bazel_2README.html',1,'']]],
  ['bdd_20style_20test_20cases_27',['BDD-style test cases',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2testcases.html#autotoc_md171',1,'']]],
  ['be_20used_20within_20the_20same_20binary_20executable_20dll_28',['Can different versions of the framework be used within the same binary (executable/dll)?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md137',1,'']]],
  ['before_20after_29',['Benchmark                                  Before             After',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md202',1,'']]],
  ['begin_30',['begin',['../classbasic__format__parse__context.html#afb21ddaa0d32b5430f99eed530666ea9',1,'basic_format_parse_context::begin()'],['../classmgutility_1_1enum__for__each.html#a1415f386351d4564317694ea55e29954',1,'mgutility::enum_for_each::begin()'],['../classmgutility_1_1basic__string__view.html#a7e457bc18a0dbd2958f740befdb9943d',1,'mgutility::basic_string_view::begin()']]],
  ['benchmark_20before_20after_31',['Benchmark                                  Before             After',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md202',1,'']]],
  ['benchmark_20time_20cpu_20iterations_32',['Benchmark Time CPU Iterations',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md207',1,'Benchmark                                  Time             CPU   Iterations'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md210',1,'Benchmark                                  Time             CPU   Iterations'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md213',1,'Benchmark                                  Time             CPU   Iterations'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md193',1,'Benchmark               Time             CPU   Iterations'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2ChangeLog.html#autotoc_md195',1,'Benchmark               Time             CPU   Iterations']]],
  ['benchmarks_33',['Benchmarks',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2benchmarks.html',1,'Benchmarks'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md257',1,'Benchmarks'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2benchmarks.html#autotoc_md59',1,'Compile time benchmarks'],['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2benchmarks.html#autotoc_md68',1,'Runtime benchmarks']]],
  ['best_20compile_20time_20performance_20with_20the_20framework_34',['How to get the best compile-time performance with the framework?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md129',1,'']]],
  ['bg_35',['bg',['../classtext__style.html#a6a305e872bd49882fde60db9cfa2fc2b',1,'text_style']]],
  ['big_5fdecimal_5ffp_36',['big_decimal_fp',['../structdetail_1_1big__decimal__fp.html',1,'detail']]],
  ['bigint_37',['bigint',['../classdetail_1_1bigint.html',1,'detail']]],
  ['binary_20and_20unary_20asserts_38',['Binary and unary asserts',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2assertions.html#autotoc_md50',1,'']]],
  ['binary_20executable_20dll_39',['Can different versions of the framework be used within the same binary (executable/dll)?',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2faq.html#autotoc_md137',1,'']]],
  ['bind_40',['Bind',['../structtesting_1_1internal_1_1TemplateSel_1_1Bind.html',1,'testing::internal::TemplateSel']]],
  ['bloat_41',['Compile time and code bloat',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md259',1,'']]],
  ['boost_20format_42',['Boost Format',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md266',1,'']]],
  ['boost_20spirit_20karma_43',['Boost Spirit.Karma',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2README.html#autotoc_md268',1,'']]],
  ['box_44',['box',['../structadl_1_1box.html',1,'adl']]],
  ['branchpattern_45',['BranchPattern',['../classdocopt_1_1BranchPattern.html',1,'docopt']]],
  ['briefunittestresultprinter_46',['BriefUnitTestResultPrinter',['../classtesting_1_1internal_1_1BriefUnitTestResultPrinter.html',1,'testing::internal']]],
  ['buffer_47',['buffer',['../classdetail_1_1buffer.html',1,'detail']]],
  ['buffer_3c_20bigit_20_3e_48',['buffer&lt; bigit &gt;',['../classdetail_1_1buffer.html',1,'detail']]],
  ['buffer_3c_20char_20_3e_49',['buffer&lt; char &gt;',['../classdetail_1_1buffer.html',1,'detail']]],
  ['buffer_3c_20char_5ftype_20_3e_50',['buffer&lt; char_type &gt;',['../classdetail_1_1buffer.html',1,'detail']]],
  ['buffer_3c_20container_3a_3avalue_5ftype_20_3e_51',['buffer&lt; Container::value_type &gt;',['../classdetail_1_1buffer.html',1,'detail']]],
  ['buffer_3c_20wchar_5ft_20_3e_52',['buffer&lt; wchar_t &gt;',['../classdetail_1_1buffer.html',1,'detail']]],
  ['buffer_5ftraits_53',['buffer_traits',['../structdetail_1_1buffer__traits.html',1,'detail']]],
  ['buffered_5ffile_54',['buffered_file',['../classbuffered__file.html',1,'']]],
  ['build_20systems_55',['Build systems',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2build-systems.html',1,'']]],
  ['builtindefaultvalue_56',['BuiltInDefaultValue',['../classtesting_1_1internal_1_1BuiltInDefaultValue.html',1,'testing::internal']]],
  ['builtindefaultvalue_3c_20const_20t_20_3e_57',['BuiltInDefaultValue&lt; const T &gt;',['../classtesting_1_1internal_1_1BuiltInDefaultValue_3_01const_01T_01_4.html',1,'testing::internal']]],
  ['builtindefaultvalue_3c_20t_20_2a_20_3e_58',['BuiltInDefaultValue&lt; T * &gt;',['../classtesting_1_1internal_1_1BuiltInDefaultValue_3_01T_01_5_01_4.html',1,'testing::internal']]],
  ['builtindefaultvaluegetter_59',['BuiltInDefaultValueGetter',['../structtesting_1_1internal_1_1BuiltInDefaultValueGetter.html',1,'testing::internal']]],
  ['builtindefaultvaluegetter_3c_20t_2c_20false_20_3e_60',['BuiltInDefaultValueGetter&lt; T, false &gt;',['../structtesting_1_1internal_1_1BuiltInDefaultValueGetter_3_01T_00_01false_01_4.html',1,'testing::internal']]],
  ['by_20type_61',['Templated test cases - parameterized by type',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2doctest-src_2doc_2markdown_2parameterized-tests.html#autotoc_md157',1,'']]],
  ['bymovewrapper_62',['ByMoveWrapper',['../structtesting_1_1internal_1_1ByMoveWrapper.html',1,'testing::internal']]],
  ['bytes_63',['bytes',['../classbytes.html',1,'']]],
  ['bzlmod_64',['Using Bzlmod',['../md__2home_2runner_2work_2enum__name_2enum__name_2build_2__deps_2fmt-src_2support_2bazel_2README.html#autotoc_md275',1,'']]]
];
