var searchData=
[
  ['saveargaction_0',['SaveArgAction',['../structtesting_1_1internal_1_1SaveArgAction.html',1,'testing::internal']]],
  ['saveargpointeeaction_1',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1SaveArgPointeeAction.html',1,'testing::internal']]],
  ['scan_5fargs_2',['scan_args',['../structscan__args.html',1,'']]],
  ['scan_5fbuffer_3',['scan_buffer',['../classdetail_1_1scan__buffer.html',1,'detail']]],
  ['scan_5fcontext_4',['scan_context',['../classscan__context.html',1,'']]],
  ['scan_5fhandler_5',['scan_handler',['../structdetail_1_1scan__handler.html',1,'detail']]],
  ['scan_5fparse_5fcontext_6',['scan_parse_context',['../classscan__parse__context.html',1,'']]],
  ['scanner_7',['scanner',['../structscanner.html',1,'']]],
  ['scanner_3c_20num_20_3e_8',['scanner&lt; num &gt;',['../structfmt_1_1scanner_3_01num_01_4.html',1,'fmt']]],
  ['scoped_5fmock_9',['scoped_mock',['../structscoped__mock.html',1,'']]],
  ['scopedprematureexitfile_10',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1ScopedPrematureExitFile.html',1,'testing::internal']]],
  ['scopedtrace_11',['ScopedTrace',['../classtesting_1_1ScopedTrace.html',1,'testing']]],
  ['sentinel_12',['sentinel',['../classdetail_1_1scan__buffer_1_1sentinel.html',1,'detail::scan_buffer']]],
  ['setargrefereeaction_13',['SetArgRefereeAction',['../structtesting_1_1internal_1_1SetArgRefereeAction.html',1,'testing::internal']]],
  ['setargumentpointeeaction_14',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1SetArgumentPointeeAction.html',1,'testing::internal']]],
  ['setarrayargumentaction_15',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1SetArrayArgumentAction.html',1,'testing::internal']]],
  ['seterrnoandreturnaction_16',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1SetErrnoAndReturnAction.html',1,'testing::internal']]],
  ['should_5fstringify_5fas_5funderlying_5ftype_17',['should_stringify_as_underlying_type',['../structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html',1,'doctest::detail']]],
  ['singleton_18',['singleton',['../structdetail_1_1singleton.html',1,'detail']]],
  ['slow_5ffloat_19',['slow_float',['../structslow__float.html',1,'']]],
  ['small_5fgrouping_20',['small_grouping',['../structsmall__grouping.html',1,'']]],
  ['somefixture_21',['SomeFixture',['../structSomeFixture.html',1,'']]],
  ['special_5fgrouping_22',['special_grouping',['../structspecial__grouping.html',1,'']]],
  ['std_5fstring_5fview_23',['std_string_view',['../structdetail_1_1std__string__view.html',1,'detail']]],
  ['stlcontainerview_24',['StlContainerView',['../classtesting_1_1internal_1_1StlContainerView.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_25',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1StlContainerView_3_01_1_1std_1_1tuple_3_01ElementPointer_00_01Size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_26',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1StlContainerView_3_01Element_0fN_0e_4.html',1,'testing::internal']]],
  ['streamable_5fand_5funformattable_27',['streamable_and_unformattable',['../structstreamable__and__unformattable.html',1,'']]],
  ['streamed_5fview_28',['streamed_view',['../structdetail_1_1streamed__view.html',1,'detail']]],
  ['streamprinter_29',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1StreamPrinter.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strictmock_30',['StrictMock',['../classtesting_1_1StrictMock.html',1,'testing']]],
  ['strictmock_3c_20mock_20_3e_31',['StrictMock&lt; Mock &gt;',['../classtesting_1_1StrictMock.html',1,'testing']]],
  ['strictmockimpl_32',['StrictMockImpl',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mock_20_3e_33',['StrictMockImpl&lt; Mock &gt;',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_34',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1StrictMockImpl.html',1,'testing::internal']]],
  ['string_35',['string',['../structadl__test_1_1string.html',1,'adl_test']]],
  ['string_36',['String',['../classdoctest_1_1String.html',1,'doctest::String'],['../classtesting_1_1internal_1_1String.html',1,'testing::internal::String']]],
  ['string_5fliteral_37',['string_literal',['../structdetail_1_1string__literal.html',1,'detail']]],
  ['string_5fscan_5fbuffer_38',['string_scan_buffer',['../classdetail_1_1string__scan__buffer.html',1,'detail']]],
  ['string_5fvalue_39',['string_value',['../structdetail_1_1string__value.html',1,'detail']]],
  ['string_5fvalue_3c_20char_5ftype_20_3e_40',['string_value&lt; char_type &gt;',['../structdetail_1_1string__value.html',1,'detail']]],
  ['stringcontains_41',['StringContains',['../classdoctest_1_1AssertData_1_1StringContains.html',1,'doctest::AssertData']]],
  ['stringmaker_42',['StringMaker',['../structdoctest_1_1StringMaker.html',1,'doctest']]],
  ['stringmaker_3c_20std_3a_3alist_3c_20t_20_3e_20_3e_43',['StringMaker&lt; std::list&lt; T &gt; &gt;',['../structdoctest_1_1StringMaker_3_01std_1_1list_3_01T_01_4_01_4.html',1,'doctest']]],
  ['stringmakerbase_44',['StringMakerBase',['../structdoctest_1_1detail_1_1StringMakerBase.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20detail_3a_3ahas_5finsertion_5foperator_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5fpointer_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5farray_3c_20t_20_3e_3a_3avalue_20_3e_45',['StringMakerBase&lt; detail::has_insertion_operator&lt; T &gt;::value||detail::types::is_pointer&lt; T &gt;::value||detail::types::is_array&lt; T &gt;::value &gt;',['../structdoctest_1_1detail_1_1StringMakerBase.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20true_20_3e_46',['StringMakerBase&lt; true &gt;',['../structdoctest_1_1detail_1_1StringMakerBase_3_01true_01_4.html',1,'doctest::detail']]],
  ['strip_5fnamed_5farg_47',['strip_named_arg',['../structdetail_1_1strip__named__arg.html',1,'detail']]],
  ['strip_5fnamed_5farg_3c_20t_2c_20true_20_3e_48',['strip_named_arg&lt; T, true &gt;',['../structdetail_1_1strip__named__arg_3_01T_00_01true_01_4.html',1,'detail']]],
  ['struct_5fas_5fconst_5freference_49',['struct_as_const_reference',['../structtest_1_1struct__as__const__reference.html',1,'test']]],
  ['struct_5fas_5fint_50',['struct_as_int',['../structtest_1_1struct__as__int.html',1,'test']]],
  ['struct_5fas_5fwstring_5fview_51',['struct_as_wstring_view',['../structtest_1_1struct__as__wstring__view.html',1,'test']]],
  ['styled_5farg_52',['styled_arg',['../structdetail_1_1styled__arg.html',1,'detail']]],
  ['subcase_53',['Subcase',['../structdoctest_1_1detail_1_1Subcase.html',1,'doctest::detail::Subcase'],['../structSubcase.html',1,'Subcase']]],
  ['subcasesignature_54',['SubcaseSignature',['../structdoctest_1_1SubcaseSignature.html',1,'doctest']]],
  ['suiteapiresolver_55',['SuiteApiResolver',['../structtesting_1_1internal_1_1SuiteApiResolver.html',1,'testing::internal']]]
];
